# Generated by Django 4.2.23 on 2025-06-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="説明"
                    ),
                ),
                ("completed", models.BooleanField(default=False, verbose_name="完了")),
                (
                    "created_Date",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "タスク",
                "verbose_name_plural": "タスク一覧",
                "db_table": "Tasks",
                "ordering": ["completed", "-created_Date"],
            },
        ),
    ]
